version: '3.5'

services:
  tor-proxy:
    image: dperson/torproxy
    container_name: tor-proxy
    restart: always
    ports:
      - "8118:8118"
      - "9050:9050"
    environment:
      - PASSWORD=webscrape
    networks:
      - tornetwork

networks:
  tornetwork:
    name: tornetwork
    driver: bridge
