version: '3.5'

services:
    selenium-sub:
        image: selenium/standalone-chrome:3.141.59-yttrium
        container_name: selenium-hub
        ports:
            - "4444:4444"

        restart: always

networks:
  default:
    external:
      name: mongonetwork